[build]
  command = "pnpm nx build web"
  publish = "dist/apps/web/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NX_NO_CLOUD = "true"
  NX_DAEMON = "false"
  CI = "true"
